### ISSUE TITLE
Highlighted text looks weird now

### ISSUE THREAD

**Issue by Narretz** [gerardroche/sublime-monokai-free#7]
I assume it's the recent update.

Highlighted text is very subtle now, and also looks "off". The background seems to sag under the line.

![Screenshot 2023-06-19 162538](https://github.com/gerardroche/sublime-monokai-free/assets/1153097/92fbfa8e-bc55-4a33-a36e-6a4db05a3402)

Can you tell me what the previous config was so I can change it back locally? Maybe it's also already an override by me?

Would also be cool if you could add release notes to the package registry, so it's easier to see what has changed.

**Comment by gerardroche** [comment]
There was recently a major update. v2. I removed support for the old tmTheme and
updated some things supported by the new color scheme format.

I'm just checking now to what changes were made to the selections.

What os are you on? And when did you get updated? v2 is now on version 2.0.2 so
I'm wondering if it was one of the the last two changes rather than the full v2
changes.

In 2.0.2 the inactive selection border was changed from yellow to be the same as
active selections at 80% opacity.

```diff
-        "inactive_selection_border": "color(var(yellow) alpha(0.8)",
+        "inactive_selection_border": "color(var(fg2) alpha(0.8))",
```

There were some changes between 1.20.7 and 2.0.0, but most were just new color
scheme format updates.

https://github.com/gerardroche/sublime-monokai-free/compare/1.20.7...master

Selections were changed from:

        "selection": "#75715e",
        "selection_foreground": "#272822",
        "selection_border": "",
        "inactive_selection": "#75715e",
        "inactive_selection_foreground": "#272822",

to


        "inactive_selection": "color(var(fg2) alpha(0.8))",
        "inactive_selection_border": "color(var(fg2) alpha(0.8))",
        "inactive_selection_foreground": "color(var(bg0) alpha(0.8))",
        "selection": "var(fg2)",
        "selection_border": "var(fg2)",
        "selection_foreground": "var(bg0)",

where

```
        "bg0": "#272822",

        "fg0": "#f8f8f2",
        "fg1": "#cfcfc2",
        "fg2": "#75715e",
```

So it's maybe a border color issue?

You can check by testing a custom override for it: https://github.com/gerardroche/sublime-monokai-free#customization

In the old scheme border was blank. Yes, when you make the border blank it seems
to add some sort of default border. Wheras the border now is the same color as
the background, so basically no border.

The border default seems to be `#575446` which looks better.

I didn't notice because I use square style selections:

```json
{
    "variables": {},
    "globals": {
        "caret": "yellow",
        "block_caret": "yellow",
        "line_highlight": "#66d9ef22",
        "block_caret_corner_style": "square",
        "selection_corner_style": "square"
    },
    "rules": []
}
```

**Comment by gerardroche** [comment]
Although your selection still looks much more subtle that it should be. Did the
update revert you back to the default monokai color scheme?

Command Palette → UI: Select color scheme

**Comment by gerardroche** [comment]
I think the update may have reverted you back to the default monokai color
scheme bundled with Sublime.

Here is a diff of what actually changed since v1, not a lot, mostly fixes
and some enhancements that were not available in the thTheme format:

https://github.com/gerardroche/sublime-monokai-free/compare/7206fa2540adaeecd48275a15617822844fc5318...master#files_bucket

**Comment by Narretz** [comment]
> I think the update may have reverted you back to the default monokai color scheme bundled with Sublime.

This is definitely possible.

I checked the color scheme select ui and actually I couldn't even select MonokaiFree correctly. It only listed a one MonokaiFree variant coming from User/Color Highlighter/themes/MonokaiFree.tmTheme (no idea how this came about)

This seems like a UI limitation where it can only handle one Color Scheme with the same name

I then set the color scheme directly in the settings `"color_scheme": "MonokaiFree.sublime-color-scheme"` and deleted the other User/Color Highlighter/themes/MonokaiFree.tmTheme, and now it works and the color scheme selector shows it correctly as selected.

This was probably a resolution error on behalf of Sublime Text.

Really strange.

**Comment by gerardroche** [comment]
Thanks. It looks like ST might have an issue with the update.

Support for the tmTheme color scheme was removed in version 2.0.  The new color
scheme format is only supported in ST version > 3.2 so only Sublime Text
versions >= 3.2 will be updated to MonokaiFree ^2.0, others will stay on
MonokaiFree ^1.0.

I think package control is not able to deal with this change properly when
updating the package.  It also looks like the bracket highlighter auto generates
a patched color scheme to support bracket hightlighting which complicate things
too.

I'll leave this issue open for while because others might be impacted by this
and the solution you posted will be helpful.

**Comment by gerardroche** [comment]
I added a changelog.

https://github.com/gerardroche/sublime-monokai-free/blob/master/CHANGELOG.md

**Comment by gerardroche** [comment]
I added a note in the readme about possible update issues. Thank for reporting this btw.
